services:
  postgres:
    image: postgres:13.13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Pg#123
      POSTGRES_USER: kubedevnews
      POSTGRES_DB: kubedevnews
  kubenews:
    image: viniciuscaol/kubenews:v1
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8081:8080
    environment:
      DB_DATABASE: kubedevnews
      DB_USERNAME: kubedevnews
      DB_PASSWORD: Pg#123
      DB_HOST: postgres

networks:
  kubenet:
    driver: bridge